version: '2'
services:
  todolist:
    container_name: todolist
    image: registry.gitlab.com/fast-cloudcomputing/16i-0188
    # restart: always
    env_file: .env
    command: gunicorn todolist:app -w 2 -b :8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  migration:
    container_name: migration
    build: .
    image: registry.gitlab.com/fast-cloudcomputing/16i-0188
    env_file: .env
    command: flask db upgrade
    depends_on:
      - todolist
